import { UserProfile, Lifestyle, HealthData } from '../App';
import { Utensils, Dumbbell, Hospital, AlertTriangle, CheckCircle, Target } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { PriorityBadge } from './ui/priority-badge';
import { calculateRecommendationPriorities } from '../utils/recommendationPriority';
import { generateDietRecommendation, calculateTotalCalories } from '../utils/dietRecommendationLogic';
import { generateExerciseRecommendation, calculateTotalCalories as calculateExerciseCalories } from '../utils/exerciseRecommendationLogic';
import { generateHospitalRecommendation } from '../utils/hospitalRecommendationLogic';
import { MealCard } from './Recommendations/MealCard';
import { ExerciseCard } from './Recommendations/ExerciseCard';
import { HospitalCard } from './Recommendations/HospitalCard';

interface RecommendationsProps {
  profile: UserProfile;
  lifestyle: Lifestyle;
  latestHealthData?: HealthData;
  onShowMap?: () => void;
}

export function Recommendations({ profile, lifestyle, latestHealthData, onShowMap }: RecommendationsProps) {
  // Calculate BMI
  const bmi = profile.weight / Math.pow(profile.height / 100, 2);

  // Calculate priorities
  const priorities = calculateRecommendationPriorities(profile, lifestyle, latestHealthData);

  // Generate detailed diet recommendation
  const dietRecommendation = generateDietRecommendation(profile, lifestyle, latestHealthData);

  // Generate detailed exercise recommendation
  const exerciseRecommendation = generateExerciseRecommendation(profile, lifestyle, latestHealthData);

  // Generate detailed hospital recommendation
  const hospitalRecommendationResult = generateHospitalRecommendation(profile, lifestyle, latestHealthData);

  // Analyze health status
  const healthIssues: string[] = [];
  const healthWarnings: string[] = [];
  
  if (latestHealthData) {
    if (latestHealthData.sodium < 135) {
      healthIssues.push('저나트륨혈증');
    } else if (latestHealthData.sodium > 145) {
      healthIssues.push('고나트륨혈증');
    }
    
    if (latestHealthData.glucose < 70) {
      healthIssues.push('저혈당');
    } else if (latestHealthData.glucose > 140) {
      healthWarnings.push('혈당 수치 높음');
    } else if (latestHealthData.glucose > 125) {
      healthWarnings.push('당뇨 전단계 의심');
    }
  }
  
  if (bmi > 25) {
    healthWarnings.push('과체중');
  } else if (bmi < 18.5) {
    healthWarnings.push('저체중');
  }
  
  if (lifestyle.smoking) {
    healthWarnings.push('흡연');
  }
  
  if (lifestyle.alcoholFrequency === 'frequent' || lifestyle.alcoholFrequency === 'daily') {
    healthWarnings.push('과도한 음주');
  }
  
  // Diet recommendations are now generated by generateDietRecommendation()
  // Exercise recommendations are now generated by generateExerciseRecommendation()
  // Hospital recommendations are now generated by generateHospitalRecommendation()

  return (
    <div className="space-y-4">
      {/* Health Status Overview */}
      {(healthIssues.length > 0 || healthWarnings.length > 0) && (
        <div className="bg-white rounded-2xl shadow-lg p-5">
          <h2 className="text-gray-900 mb-3">건강 상태 요약</h2>
          
          {healthIssues.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-3 mb-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-red-600 mt-0.5 flex-shrink-0" />
                <div className="flex-1">
                  <p className="text-sm text-red-900 mb-1">즉시 주의 필요</p>
                  {healthIssues.map((issue, index) => (
                    <p key={index} className="text-xs text-red-700">• {issue}</p>
                  ))}
                </div>
              </div>
            </div>
          )}
          
          {healthWarnings.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-yellow-600 mt-0.5 flex-shrink-0" />
                <div className="flex-1">
                  <p className="text-sm text-yellow-900 mb-1">주의 사항</p>
                  {healthWarnings.map((warning, index) => (
                    <p key={index} className="text-xs text-yellow-700">• {warning}</p>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Recommendations with Accordion */}
      <Accordion type="multiple" className="space-y-3">
        {/* Diet Recommendations */}
        <AccordionItem value="diet" className="bg-white rounded-2xl shadow-lg overflow-hidden border-none">
          <AccordionTrigger className="px-5 py-4 hover:no-underline">
            <div className="flex items-center gap-3 flex-1">
              <div className="bg-orange-100 p-2.5 rounded-xl">
                <Utensils className="w-5 h-5 text-orange-600" />
              </div>
              <div className="flex-1 text-left">
                <h2 className="text-gray-900">맞춤 식단 추천</h2>
                <p className="text-xs text-gray-600">건강 데이터 기반</p>
              </div>
              <PriorityBadge priority={priorities.diet} />
            </div>
          </AccordionTrigger>
          <AccordionContent className="px-5 pb-5">
            {/* Diet Type and Daily Target */}
            <div className="mb-5 p-4 bg-gradient-to-r from-orange-50 to-orange-100 rounded-xl">
              <div className="flex items-center gap-2 mb-2">
                <Target className="w-4 h-4 text-orange-600" />
                <h3 className="font-semibold text-gray-900">{dietRecommendation.dietType}</h3>
              </div>
              <p className="text-sm text-gray-700 mb-3">
                일일 권장 칼로리: <span className="font-semibold text-orange-700">{dietRecommendation.dailyCalorieTarget}kcal</span>
              </p>
              <div className="space-y-1.5">
                {dietRecommendation.guidelines.map((guideline, index) => (
                  <div key={index} className="flex items-start gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-orange-600 mt-0.5 flex-shrink-0" />
                    <p className="text-xs text-gray-700">{guideline}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Meal Cards */}
            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-gray-900 mb-3">오늘의 추천 식단</h4>
              {dietRecommendation.recommendedMeals.map((meal) => (
                <MealCard key={meal.id} meal={meal} />
              ))}

              {/* Total Calories */}
              {dietRecommendation.recommendedMeals.length > 0 && (
                <div className="mt-4 p-3 bg-orange-50 rounded-lg border border-orange-200">
                  <p className="text-sm text-gray-700">
                    <span className="font-semibold">총 칼로리:</span> {calculateTotalCalories(dietRecommendation.recommendedMeals)}kcal
                    <span className="text-xs text-gray-600 ml-2">
                      (목표: {dietRecommendation.dailyCalorieTarget}kcal)
                    </span>
                  </p>
                </div>
              )}
            </div>
          </AccordionContent>
        </AccordionItem>

        {/* Exercise Recommendations */}
        <AccordionItem value="exercise" className="bg-white rounded-2xl shadow-lg overflow-hidden border-none">
          <AccordionTrigger className="px-5 py-4 hover:no-underline">
            <div className="flex items-center gap-3 flex-1">
              <div className="bg-green-100 p-2.5 rounded-xl">
                <Dumbbell className="w-5 h-5 text-green-600" />
              </div>
              <div className="flex-1 text-left">
                <h2 className="text-gray-900">맞춤 운동 추천</h2>
                <p className="text-xs text-gray-600">건강 상태 맞춤</p>
              </div>
              <PriorityBadge priority={priorities.exercise} />
            </div>
          </AccordionTrigger>
          <AccordionContent className="px-5 pb-5">
            {/* Exercise Routine Info */}
            <div className="mb-5 p-4 bg-gradient-to-r from-green-50 to-green-100 rounded-xl">
              <div className="flex items-center gap-2 mb-2">
                <Target className="w-4 h-4 text-green-600" />
                <h3 className="font-semibold text-gray-900">{exerciseRecommendation.routineName}</h3>
              </div>
              <p className="text-sm text-gray-700 mb-3">{exerciseRecommendation.description}</p>
              <div className="grid grid-cols-2 gap-3 mb-3">
                <div className="text-sm">
                  <span className="text-gray-600">운동 빈도:</span>
                  <span className="ml-2 font-semibold text-green-700">{exerciseRecommendation.frequency}</span>
                </div>
                <div className="text-sm">
                  <span className="text-gray-600">1회 시간:</span>
                  <span className="ml-2 font-semibold text-green-700">{exerciseRecommendation.totalDuration}분</span>
                </div>
              </div>
              <div className="mb-3 p-3 bg-white rounded-lg">
                <p className="text-sm text-gray-700">
                  <span className="font-semibold">주간 목표:</span> {exerciseRecommendation.weeklyGoal}
                </p>
              </div>
              <div className="space-y-1.5">
                {exerciseRecommendation.guidelines.map((guideline, index) => (
                  <div key={index} className="flex items-start gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-green-600 mt-0.5 flex-shrink-0" />
                    <p className="text-xs text-gray-700">{guideline}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Exercise Cards */}
            <div className="space-y-4">
              <h4 className="text-sm font-semibold text-gray-900 mb-3">추천 운동 목록</h4>
              {exerciseRecommendation.recommendedExercises.map((exercise) => (
                <ExerciseCard key={exercise.id} exercise={exercise} />
              ))}

              {/* Total Calories */}
              {exerciseRecommendation.recommendedExercises.length > 0 && (
                <div className="mt-4 p-3 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-sm text-gray-700">
                    <span className="font-semibold">예상 소모 칼로리:</span> {calculateExerciseCalories(exerciseRecommendation.recommendedExercises)}kcal
                    <span className="text-xs text-gray-600 ml-2">
                      (1회 운동 시)
                    </span>
                  </p>
                </div>
              )}
            </div>
          </AccordionContent>
        </AccordionItem>

        {/* Hospital Recommendations */}
        <AccordionItem value="hospital" className="bg-white rounded-2xl shadow-lg overflow-hidden border-none">
          <AccordionTrigger className="px-5 py-4 hover:no-underline">
            <div className="flex items-center gap-3 flex-1">
              <div className="bg-red-100 p-2.5 rounded-xl">
                <Hospital className="w-5 h-5 text-red-600" />
              </div>
              <div className="flex-1 text-left">
                <h2 className="text-gray-900">병원 방문 안내</h2>
                <p className="text-xs text-gray-600">전문 의료진 상담</p>
              </div>
              <PriorityBadge priority={priorities.hospital} />
            </div>
          </AccordionTrigger>
          <AccordionContent className="px-5 pb-5">
            {/* Summary */}
            <div className="mb-5 p-4 bg-gradient-to-r from-red-50 to-red-100 rounded-xl">
              <div className="flex items-center gap-2 mb-2">
                <Target className="w-4 h-4 text-red-600" />
                <h3 className="font-semibold text-gray-900">건강 상태 종합</h3>
              </div>
              <p className="text-sm text-gray-700">{hospitalRecommendationResult.summary}</p>
            </div>

            {/* Primary Recommendation */}
            <div className="space-y-4">
              <div>
                <h4 className="text-sm font-semibold text-gray-900 mb-3">주요 권장 사항</h4>
                <HospitalCard recommendation={hospitalRecommendationResult.primaryRecommendation} onShowMap={onShowMap} />
              </div>

              {/* Additional Recommendations */}
              {hospitalRecommendationResult.additionalRecommendations.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold text-gray-900 mb-3">
                    추가 관리 항목 ({hospitalRecommendationResult.additionalRecommendations.length}건)
                  </h4>
                  <div className="space-y-3">
                    {hospitalRecommendationResult.additionalRecommendations.map((recommendation) => (
                      <HospitalCard key={recommendation.id} recommendation={recommendation} onShowMap={onShowMap} />
                    ))}
                  </div>
                </div>
              )}
            </div>
          </AccordionContent>
        </AccordionItem>
      </Accordion>

      {/* Disclaimer */}
      <div className="bg-gray-100 rounded-xl p-4">
        <p className="text-xs text-gray-600">
          ⚠️ 본 추천은 참고용이며 의학적 진단을 대체할 수 없습니다. 건강 이상 시 전문 의료진과 상담하세요.
        </p>
      </div>
    </div>
  );
}